### ISSUE TITLE
GitHub label copying utility

### ISSUE THREAD

**Issue by lundibundi** [metarhia/tools#4]
A Tool to synchronize labels in multiple repositories.
It should request all labels from the specified source repo and then add/replace all of them in the target repos.

Edit: it should basically use GitHub API [list-all-labels-for-this-repository](https://developer.github.com/v3/issues/labels/#list-all-labels-for-this-repository), [create-a-label](https://developer.github.com/v3/issues/labels/#create-a-label) and [update-a-label](https://developer.github.com/v3/issues/labels/#update-a-label) if requested.

/cc @belochub @nechaido

**Comment by SemenchenkoVitaliy** [comment]
Also, it would also be nice to be able to add/replace labels from a predefined set in specified repos.

**Comment by SemenchenkoVitaliy** [comment]
Closed in https://github.com/metarhia/tools/pull/5.
